name: Build Android APK

on:
  push:
    branches: [ main ]

env:
  BUILDODER_DIR: /home/runner/work/${{ github.repository }}/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libtinfo6 cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33

    - name: Run Buildozer init
      run: |
        buildozer init
        # 确保使用正确的配置
        echo -e "\n[app]\nandroid.archs = arm64-v8a\n" >> buildozer.spec

    - name: Build APK (with debug)
      run: |
        buildozer -v android clean
        buildozer -v android debug 2>&1 | tee build.log
        grep -i "BUILD SUCCESSFUL" build.log || (cat build.log && exit 1)

    - name: Find and list APK
      run: |
        find . -name "*.apk" -exec ls -lh {} \;
        mkdir -p artifacts
        cp bin/*.apk artifacts/ || true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: artifacts/*.apk
        if-no-files-found: error
